### ISSUE TITLE
requirement.txt is missing in the repo

### ISSUE THREAD

**Issue by nithyadurai87** [artdevgame/tesseract-trainer#1]
Docker is looking for requirement.txt

add that into the repo.

getting the below error.

Step 5/12 : WORKDIR /app
 ---> Running in 7ce6b5b7ff83
Removing intermediate container 7ce6b5b7ff83
 ---> 02b9b4b22f64
Step 6/12 : COPY requirements.txt ./
ERROR: Service 'app' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder060333001/requirements.txt: no such file or directory

**Comment by mzkaramat** [comment]
@nithyadurai87 i commented this line and it worked for me

**Comment by ministerofpanic** [comment]
Thank you for bringing this to my attention and sorry it has taken me so long to address, I missed the notification.
I've taken the offending line out of the Dockerfile now.
