### ISSUE TITLE
How to train for Tamil Language font?

### ISSUE THREAD

**Issue by tshrinivasan** [artdevgame/tesseract-trainer#2]
used the Vijaya.ttf here
https://fontsnetwork.com/download/vijaya-zip/

Added these lines in docker-compose.yml

     - TESSTRAIN_FONT=Vijaya
      - TESSTRAIN_LANG=tam

Added the ttf file in src/fonts

For the missing requirement.txt #1 used the below file
https://github.com/guiem/train-tesseract/blob/master/requirements.txt

in Dockerfile added as below

>   cd /usr/local/share/tessdata && wget https://github.com/tesseract-ocr/tessdata_best/raw/master/eng.traineddata && \
>   wget https://github.com/tesseract-ocr/tessdata_best/raw/master/tam.traineddata
> 

Still I am getting below error finally,

> train-ocr | 
> train-ocr | Created starter traineddata for LSTM training of language 'tam'
> train-ocr | 
> train-ocr | 
> train-ocr | Run 'lstmtraining' command to continue LSTM training for language 'tam'
> train-ocr | 
> train-ocr | Failed to read /usr/local/share/tessdata/tam.traineddata
> train-ocr | /app/src/train/tam.lstm is not a recognition model, trying training checkpoint...
> train-ocr | Failed to load language model from /usr/local/share/tessdata/tam.traineddata!
> train-ocr | mgr_.Init(traineddata_path.c_str()):Error:Assert failed:in file lstmtrainer.h, line 96
> train-ocr | Aborted (core dumped)
> train-ocr | mgr_.Init(traineddata_path.c_str()):Error:Assert failed:in file lstmtrainer.h, line 96
> train-ocr | Aborted (core dumped)
> train-ocr | /app/src/output/_checkpoint is not a recognition model, trying training checkpoint...
> train-ocr | Failed to load language model from /usr/local/share/tessdata/tam.traineddata!
> 

Check this and help to fix the issue.

Thanks.

**Comment by raghada** [comment]
Hey! I'm having the same problem with Arabic, were you be able to solve it? thanks.

**Comment by ministerofpanic** [comment]
Sorry for the very late reply @tshrinivasan, I've only just noticed your ticket. Did you manage to resolve this on your own?

Honestly, I don't know what the solution is, but I'd hazard a guess that is has something to do with the system languages installed, try changing the Dockerfile around here: https://github.com/artdevgame/tesseract-trainer/blob/master/Dockerfile#L29
