### ISSUE TITLE
404 when downloading tessdata_best

### ISSUE THREAD

**Issue by Malkiz223** [artdevgame/tesseract-trainer#5]
Hey! I tried to start the container, but during the build I got the following error:

```
#9 484.0 libtool: install: /usr/bin/install -c .libs/cntraining /usr/local/bin/cntraining
#9 484.1 libtool: install: /usr/bin/install -c .libs/mftraining /usr/local/bin/mftraining
#9 484.1 libtool: install: /usr/bin/install -c .libs/shapeclustering /usr/local/bin/shapeclustering
#9 484.1 --2021-11-07 11:15:39--  https://github.com/tesseract-ocr/tessdata_best/raw/master/eng.traineddata
#9 484.1 Resolving github.com (github.com)... 140.82.121.3
#9 484.1 Connecting to github.com (github.com)|140.82.121.3|:443... connected.
#9 484.2 HTTP request sent, awaiting response... 404 Not Found
#9 484.6 2021-11-07 11:15:40 ERROR 404: Not Found.
#9 484.6
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c mkdir src && cd /app/src &&   git clone https://github.com/tesseract-ocr/tesseract.git &&   cd /app/src/tesseract && ./autogen.sh && ./configure -
-disable-graphics && make && make install && ldconfig &&   make training && make training-install &&   cd /usr/local/share/tessdata && wget https://github.com/tesseract-ocr/tessdata_best/raw/master/eng.traineddata]: exit code: 8
```

It is related to the fact that the main branch has been renamed from `master` to `main`.

If in Dockerfile change
`wget https://github.com/tesseract-ocr/tessdata_best/raw/master/eng.traineddata`
on
`wget https://github.com/tesseract-ocr/tessdata_best/raw/main/eng.traineddata`
the problem will be solved.

But I have a question: should I change the name of this file from `eng` to `rus`, if I want to teach the model for the Russian language?

**Comment by ministerofpanic** [comment]
Thanks for the heads up @Malkiz223, I'll try & get that sorted.

I *think* changing `eng` to `rus` is the correct approach but I haven't really tested other languages, so your mileage may vary.
